# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kUq2_QLZS0O2usjU8Slf9ltOx8lXKeqE
"""

import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras import layers, models


(train_ds, val_ds), ds_info = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:]'],
    with_info=True,
    as_supervised=True
)


IMG_SIZE = 150
BATCH_SIZE = 32

def format_image(image, label):

    image = tf.cast(image, tf.float32) / 255.0

    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    return image, label


train_ds = train_ds.map(format_image).shuffle(1000).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.map(format_image).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)


model = models.Sequential([

    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    layers.MaxPooling2D(2, 2),


    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),


    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),


    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5), 
    layers.Dense(1, activation='sigmoid') 


model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


EPOCHS = 10
history = model.fit(
    train_ds,
    epochs=EPOCHS,
    validation_data=val_ds
)
